# Generated by Django 5.2.6 on 2025-09-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_userstockselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstockselection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
