# Generated by Django 5.2.6 on 2025-11-19 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_conversation_chatbot_con_user_id_0be7ed_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_loss_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='chatbot.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', '-created_at'], name='chatbot_por_portfol_d5439b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Símbolo do ativo (ex: AAPL, MSFT)', max_length=20)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantidade de ações/ativos', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço unitário na transação', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notas opcionais sobre a transação')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='chatbot.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', '-created_at'], name='chatbot_tra_portfol_42fc6f_idx'), models.Index(fields=['symbol'], name='chatbot_tra_symbol_037dda_idx')],
            },
        ),
    ]
