# Generated by Django 5.2.6 on 2025-09-15 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_investidor', models.CharField(choices=[('CONSERVADOR', 'Conservador'), ('MODERADO', 'Moderado'), ('AGRESSIVO', 'Agressivo'), ('NAO_DEFINIDO', 'Não Definido')], default='NAO_DEFINIDO', max_length=20)),
                ('questionario_completo', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
